# Aerospace tiling window manager for macOS.
# Keybindings mirror Hyprland (Linux) using Hyper (Ctrl+Alt+Cmd via Karabiner).
{
  config,
  lib,
  pkgs,
  ...
}:
with lib; let
  cfg = config.features.desktop.aerospace;
  kb = import ./keybindings.nix;
  workspaceNames = map toString (range 1 10);
  persistentWorkspaces = workspaceNames ++ ["S"];
  aerospaceBin = "/opt/homebrew/bin/aerospace";
  workspaceCycleNext = pkgs.writeShellApplication {
    name = "aerospace-workspace-next";
    text = ''
      cat <<'EOF' | ${aerospaceBin} workspace --wrap-around --stdin next
      ${concatStringsSep "\n" workspaceNames}
      EOF
    '';
  };
  workspaceCyclePrev = pkgs.writeShellApplication {
    name = "aerospace-workspace-prev";
    text = ''
      cat <<'EOF' | ${aerospaceBin} workspace --wrap-around --stdin prev
      ${concatStringsSep "\n" workspaceNames}
      EOF
    '';
  };
  lockScreen = pkgs.writeShellApplication {
    name = "aerospace-lock-screen";
    text = ''
      exec "/System/Library/CoreServices/Menu Extras/User.menu/Contents/Resources/CGSession" -suspend
    '';
  };
  scratchTerminal = pkgs.writeShellApplication {
    name = "aerospace-scratch-terminal";
    runtimeInputs = [pkgs.jq];
    text = ''
      current_workspace="$(${aerospaceBin} list-workspaces --focused --format '%{workspace}' 2>/dev/null || true)"

      if [ "$current_workspace" = "S" ]; then
        exec ${aerospaceBin} workspace-back-and-forth
      fi

      if ${aerospaceBin} list-windows --workspace S --format '%{app-name}' 2>/dev/null | grep -Fxq Ghostty; then
        exec ${aerospaceBin} workspace --auto-back-and-forth S
      fi

      before_ids="$(${aerospaceBin} list-windows --all --json 2>/dev/null | jq '[.[] | select(."app-name" == "Ghostty") | ."window-id"]')"

      ${aerospaceBin} workspace S
      open -na Ghostty

      for _ in $(seq 1 50); do
        new_id="$(${aerospaceBin} list-windows --all --json 2>/dev/null | jq -r --argjson before "$before_ids" '[.[] | select(."app-name" == "Ghostty" and (.["window-id"] as $id | ($before | index($id) | not))) | ."window-id"] | max // empty')"
        if [ -n "$new_id" ]; then
          ${aerospaceBin} move-node-to-workspace --window-id "$new_id" S
          exec ${aerospaceBin} focus --window-id "$new_id"
        fi
        sleep 0.1
      done

      exec ${aerospaceBin} workspace --auto-back-and-forth S
    '';
  };

  # Build workspace-to-app TOML blocks for macOS (matches by app display name)
  appAssignments = concatStringsSep "\n" (
    mapAttrsToList (ws: def:
      concatStringsSep "\n" (
        map (app: "[[on-window-detected]]\nif.app-name-regex-substring = '${app}'\nrun = 'move-node-to-workspace ${ws}'")
        def.darwin
      )
    ) kb.workspaces
  );
in {
  options.features.desktop.aerospace.enable =
    mkEnableOption "Aerospace tiling window manager configuration";

  config =
    mkIf cfg.enable
    (mkIf pkgs.stdenv.isDarwin {
      xdg.configFile."aerospace/aerospace.toml".text = ''
        # Aerospace configuration — generated by home-manager
        # Mirrors Hyprland keybindings via shared keybindings.nix

        config-version = 2
        start-at-login = true
        after-login-command = []
        after-startup-command = []
        persistent-workspaces = [${concatMapStringsSep ", " (ws: "'${ws}'") persistentWorkspaces}]

        # BSP tiling (closest to Hyprland dwindle)
        default-root-container-layout = 'tiles'
        default-root-container-orientation = 'auto'

        # Match Hyprland gaps
        [gaps]
        inner.horizontal = 5
        inner.vertical = 5
        outer.left = 10
        outer.right = 10
        outer.top = 10
        outer.bottom = 10

        # --- App Assignments (must be before [mode] sections in TOML) ---------------
        ${appAssignments}

        # --- Keybindings ---------------------------------------------------------
        # Hyper = ctrl-alt-cmd (physical Ctrl key via Karabiner)

        [mode.main.binding]
        # Workspace switching
        ctrl-alt-cmd-1 = 'workspace 1'
        ctrl-alt-cmd-2 = 'workspace 2'
        ctrl-alt-cmd-3 = 'workspace 3'
        ctrl-alt-cmd-4 = 'workspace 4'
        ctrl-alt-cmd-5 = 'workspace 5'
        ctrl-alt-cmd-6 = 'workspace 6'
        ctrl-alt-cmd-7 = 'workspace 7'
        ctrl-alt-cmd-8 = 'workspace 8'
        ctrl-alt-cmd-9 = 'workspace 9'
        ctrl-alt-cmd-0 = 'workspace 10'
        ctrl-alt-cmd-comma = 'exec-and-forget ${workspaceCyclePrev}/bin/aerospace-workspace-prev'
        ctrl-alt-cmd-period = 'exec-and-forget ${workspaceCycleNext}/bin/aerospace-workspace-next'

        # Move window to workspace
        ctrl-alt-cmd-shift-1 = 'move-node-to-workspace 1'
        ctrl-alt-cmd-shift-2 = 'move-node-to-workspace 2'
        ctrl-alt-cmd-shift-3 = 'move-node-to-workspace 3'
        ctrl-alt-cmd-shift-4 = 'move-node-to-workspace 4'
        ctrl-alt-cmd-shift-5 = 'move-node-to-workspace 5'
        ctrl-alt-cmd-shift-6 = 'move-node-to-workspace 6'
        ctrl-alt-cmd-shift-7 = 'move-node-to-workspace 7'
        ctrl-alt-cmd-shift-8 = 'move-node-to-workspace 8'
        ctrl-alt-cmd-shift-9 = 'move-node-to-workspace 9'
        ctrl-alt-cmd-shift-0 = 'move-node-to-workspace 10'

        # Window focus (arrow keys)
        ctrl-alt-cmd-left = 'focus left'
        ctrl-alt-cmd-right = 'focus right'
        ctrl-alt-cmd-down = 'focus down'
        ctrl-alt-cmd-up = 'focus up'

        # Window movement (arrow keys + shift)
        ctrl-alt-cmd-shift-left = 'move left'
        ctrl-alt-cmd-shift-right = 'move right'
        ctrl-alt-cmd-shift-down = 'move down'
        ctrl-alt-cmd-shift-up = 'move up'

        # Window state
        ctrl-alt-cmd-f = 'fullscreen'
        ctrl-alt-cmd-space = 'layout floating tiling'
        ctrl-alt-cmd-w = 'close'
        ctrl-alt-cmd-l = 'exec-and-forget ${lockScreen}/bin/aerospace-lock-screen'

        # Launch terminal
        ctrl-alt-cmd-enter = 'exec-and-forget open -a Ghostty'

        # App launcher (Raycast)
        ctrl-alt-cmd-d = 'exec-and-forget open -a Raycast'

        # File manager
        ctrl-alt-cmd-e = 'exec-and-forget open -a Finder'

        # Scratch workspace toggle
        # If no Ghostty exists on S yet, create one and move it there as an exception
        # to the normal workspace-5 Ghostty assignment.
        ctrl-alt-cmd-backtick = 'exec-and-forget ${scratchTerminal}/bin/aerospace-scratch-terminal'

      '';
    });
}
